version: '3.1'
services:
  ngnix-ui:
    image: 'nginx'
    container_name: ngnix-ui
    ports:
      - '8081:80'
    volumes:
      - './nginx-ui/html:/usr/share/nginx/html'
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  baas-sample-api:
    image: resulguldibi/baas-sample-api
    container_name: baas-sample-api
    restart: always
    depends_on:
      - kafka
      - redis
      - cassandra
    links:
      - kafka
      - redis
      - cassandra
    ports:
      - '8080:8080'
  cassandra:
    image: cassandra
    container_name: cassandra
    restart: always
    ports:
      - '9042:9042'
    environment:
      CASSANDRA_CLUSTER_NAME: my_cluster
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: my_datacenter
  redis:
    image: redis:5.0.5
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379/tcp'